import { PassportPreset, PhotoSettingsState, A4LayoutSettings, StudioSettings } from '../types';

export const DEFAULT_PRESETS: PassportPreset[] = [
  {
    id: "bangladesh_passport",
    name: "Bangladesh Passport",
    country: "Bangladesh",
    width_mm: 35.0,
    height_mm: 45.0,
    unit: "mm",
    default_dpi: 300,
    description: "35 × 45 mm (Standard BD E-Passport & MRP)",
  },
  {
    id: "standard_passport",
    name: "Standard Passport (ICAO / EU / UK)",
    country: "International / UK / EU / Australia",
    width_mm: 35.0,
    height_mm: 45.0,
    unit: "mm",
    default_dpi: 300,
    description: "35 × 45 mm (Biometric Standard ICAO 9303)",
  },
  {
    id: "us_passport",
    name: "US Passport / Visa (2×2 inch)",
    country: "United States / India / Philippines",
    width_mm: 50.8,
    height_mm: 50.8,
    unit: "inch",
    default_dpi: 300,
    description: "51 × 51 mm / 2 × 2 inch (Square Passport Photo)",
  },
  {
    id: "schengen_visa",
    name: "Schengen Visa (35×45 mm)",
    country: "European Schengen Area",
    width_mm: 35.0,
    height_mm: 45.0,
    unit: "mm",
    default_dpi: 300,
    description: "35 × 45 mm (Light gray or white background)",
  },
  {
    id: "visa_40x50",
    name: "Visa (40×50 mm)",
    country: "Singapore / Russia / Canada Visa",
    width_mm: 40.0,
    height_mm: 50.0,
    unit: "mm",
    default_dpi: 300,
    description: "40 × 50 mm Portrait",
  },
  {
    id: "visa_45x55",
    name: "Visa (45×55 mm)",
    country: "Saudi Arabia / Malaysia / Japan",
    width_mm: 45.0,
    height_mm: 55.0,
    unit: "mm",
    default_dpi: 300,
    description: "45 × 55 mm Large Portrait",
  },
  {
    id: "custom",
    name: "Custom Dimensions",
    country: "Custom",
    width_mm: 35.0,
    height_mm: 45.0,
    unit: "mm",
    default_dpi: 300,
    description: "User-defined width, height, and unit (mm / inch / px)",
  },
];

export const INITIAL_PHOTO_SETTINGS: PhotoSettingsState = {
  preset_id: "bangladesh_passport",
  photo_width_mm: 35.0,
  photo_height_mm: 45.0,
  unit: "mm",
  dpi: 300,
  background_type: "white",
  background_color: "#FFFFFF",
  auto_enhance: true,
  brightness: 0,
  contrast: 0,
  sharpness: 0,
  saturation: 0,
  exposure: 0,
  smooth_skin: true,
  auto_align: true,
  manual_crop: {
    zoom: 1.0,
    offset_x: 0,
    offset_y: 0,
    rotation: 0,
  },
};

export const INITIAL_A4_SETTINGS: A4LayoutSettings = {
  paper_size: "A4",
  orientation: "portrait",
  photos_per_row: 4,
  horizontal_gap_mm: 4.0,
  vertical_gap_mm: 4.0,
  margin_top_mm: 10.0,
  margin_bottom_mm: 10.0,
  margin_left_mm: 10.0,
  margin_right_mm: 10.0,
  dpi: 300,
  show_cut_lines: true,
  copies_count: 12,
  page_index: 0,
};

export const INITIAL_STUDIO_SETTINGS: StudioSettings = {
  defaultPreset: "bangladesh_passport",
  defaultBackground: "white",
  defaultDpi: 300,
  defaultPhotosPerRow: 4,
  defaultGap: 4.0,
  defaultMargin: 10.0,
  autoEnhance: true,
  autoAlign: true,
  outputFormat: "jpg",
  apiKey: "",
  removeBgApiKey: "",
};
